services:
  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT}:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_PATH=${DB_PATH}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./data:/data
    depends_on:
      - database
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - frontend_dist:/app/dist
      - ./frontend/src:/app/src
    networks:
      - transcendence_network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - frontend_dist:/var/www/html:ro
    networks:
      - transcendence_network
    depends_on:
      - frontend

volumes:
  frontend_dist:

networks:
  transcendence_network:
    driver: bridge
